name: AI Test Generation

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  ai-testgen:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run AI TestGen Pipeline
        uses: Tejas4560/Tech_Demo/.github/workflows/ai-test-pipeline.yml@TEST2
        with:
          repo_url: ${{ github.event.repository.clone_url }}
          repo_branch: ${{ github.ref_name }}
          min_coverage: 80
        secrets:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
